package com.kent.android.slim.sample.letv.desktopmanager.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 


import android.text.TextUtils;

/**
 * Entity mapped to table SCREEN_INFO.
 */
public class ScreenInfo {
    private static final String TAG = ScreenInfo.class.getSimpleName();

    public static final String PLUGIN_STATE_CRASH = "crash";
    public static final String PLUGIN_STATE_AVAILABLE = "available";
    public static final String PLUGIN_STATE_OFFLINE = "offline";
    public static final String PLUGIN_STATE_LOADERROR = "load_error";

    public static final String PLUGIN_TYPE_DEV = "dev";

    public static final String OFFLINE_STATE_NOCHANGE = "nochange";
    public static final String OFFLINE_STATE_HASCHANGE = "haschange";

    private Long id;
    private String tag;
    private String name;
    private Boolean local;
    private Boolean sortable;
    private Boolean removable;
    private String pluginUrl;
    private Integer pluginId;
    private String pluginPath;
    private String pluginType;
    private String pluginSize;
    private String pluginState;
    private String updateType;
    private String versionName;
    // 44s
    private Integer screenOrder;
    /**
     * 多语言 tag名称，JSON格式 viewName:{"viewName": [ { "lang": "zh-CN","content": "乐见" }, { "lang":
     * "en-US", "content": "LeView" } ]}
     * {@link BaseInfo#getViewNameJson()}
     */
    private String screenTag;
    private String dependModel;
    private String versionCode;
    private String fileName;
    private String packageName;
    private String tabName;
    private String baseVersion;
    private String updateVersionCode;
    private Boolean showOnTab;
    private String fileSize;
    private String md5;
    /**
     * 插件角标图、hot等角标 {@link BaseInfo#getDesktopCornerPic()}
     */
    private String tagType;
    /**
     * 插件描述，JSON格式 description:{"description" :""}
     * {@link BaseInfo#getDescription()}
     */
    private String describe;
    /**
     * 使用中的桌面的icon {@link BaseInfo#getDesktopIconSelected()}
     */
    private String iconUrl;
    /**
     * 插件效果图 {@link BaseInfo#getDesktopEffectPic()}
     */
    private String imageUrl;
    /**
     * 更新日志，JSON格式 updateComment:{"updateComment" :""}
     * {@link com.stv.plugin.upgrade.db.bean.UpgradeRecord#getUpdateComment()}
     */
    private String updateInfo;
    private Boolean locked;
    private Boolean isNew;
    private Integer hot;
    private String notSupport;
    /** 内置fragment类全路径名 */
    private String mark1;
    /**
     * 待添加桌面的icon的图标 {@link BaseInfo#getDesktopIconUnselected()}
     */
    private String mark2;
    /**
     * 桌面的icon {@link BaseInfo#getDesktopIcon()}
     */
    private String mark3;
    private String mark4;
    // 57s
    /** 服务端下发的插件位置 */
    private Integer position;
    /** 插件是否使用过，在开机加速和桌面管理中操作完，如果showOnTable为true则表明用过 */
    private Boolean hasUsed;
    /** 插件下线时候的插件顺序快照 */
    private String offlineShot;
    /** 强制更新正在显示的桌面位置,需要先判断是否强制显示 */
    private boolean forceChangeTab;
    /** 如果插件没有用过是否强制显示 */
    private boolean forceAddToTable;

    private boolean forceUpdateFromXml;

    /** cms页面id */
    private String pageId;

    public ScreenInfo() {
    }

    public ScreenInfo(Long id) {
        this.id = id;
    }

    public ScreenInfo(Long id, String tag, String name, Boolean local, Boolean sortable,
                      Boolean removable, String pluginUrl, Integer pluginId, String pluginPath,
                      String pluginType, String pluginSize, String pluginState, String updateType,
                      String versionName, Integer screenOrder, String screenTag, String dependModel,
                      String versionCode, String fileName, String packageName, String tabName,
                      String baseVersion, String updateVersionCode, Boolean showOnTab, String fileSize,
                      String md5, String tagType, String describe, String iconUrl, String imageUrl,
                      String updateInfo, Boolean locked, Boolean isNew, Integer hot, String notSupport,
                      String mark1, String mark2, String mark3, String mark4, Integer position,
                      Boolean hasUsed, String offlineShot, String pageId) {
        this.id = id;
        this.tag = tag;
        this.name = name;
        this.local = local;
        this.sortable = sortable;
        this.removable = removable;
        this.pluginUrl = pluginUrl;
        this.pluginId = pluginId;
        this.pluginPath = pluginPath;
        this.pluginType = pluginType;
        this.pluginSize = pluginSize;
        this.pluginState = pluginState;
        this.updateType = updateType;
        this.versionName = versionName;
        this.screenOrder = screenOrder;
        this.screenTag = screenTag;
        this.dependModel = dependModel;
        this.versionCode = versionCode;
        this.fileName = fileName;
        this.packageName = packageName;
        this.tabName = tabName;
        this.baseVersion = baseVersion;
        this.updateVersionCode = updateVersionCode;
        this.showOnTab = showOnTab;
        this.fileSize = fileSize;
        this.md5 = md5;
        this.tagType = tagType;
        this.describe = describe;
        this.iconUrl = iconUrl;
        this.imageUrl = imageUrl;
        this.updateInfo = updateInfo;
        this.locked = locked;
        this.isNew = isNew;
        this.hot = hot;
        this.notSupport = notSupport;
        this.mark1 = mark1;
        this.mark2 = mark2;
        this.mark3 = mark3;
        this.mark4 = mark4;
        this.position = position;
        this.hasUsed = hasUsed;
        this.offlineShot = offlineShot;
        this.pageId = pageId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getLocal() {
        return checkBoolean(local);
    }

    public void setLocal(Boolean local) {
        this.local = local;
    }

    public Boolean getSortable() {
        return checkBoolean(sortable);
    }

    public void setSortable(Boolean sortable) {
        this.sortable = sortable;
    }

    public Boolean getRemovable() {
        return checkBoolean(removable);
    }

    public void setRemovable(Boolean removable) {
        this.removable = removable;
    }

    public String getPluginUrl() {
        return pluginUrl;
    }

    public void setPluginUrl(String pluginUrl) {
        this.pluginUrl = pluginUrl;
    }

    public Integer getPluginId() {
        return pluginId;
    }

    public void setPluginId(Integer pluginId) {
        this.pluginId = pluginId;
    }

    public String getPluginPath() {
        return pluginPath;
    }

    public void setPluginPath(String pluginPath) {
        this.pluginPath = pluginPath;
    }

    public String getPluginType() {
        return pluginType;
    }

    public void setPluginType(String pluginType) {
        this.pluginType = pluginType;
    }

    public String getPluginSize() {
        return pluginSize;
    }

    public void setPluginSize(String pluginSize) {
        this.pluginSize = pluginSize;
    }

    public String getPluginState() {
        return pluginState;
    }

    public void setPluginState(String pluginState) {
        this.pluginState = pluginState;
    }

    public String getUpdateType() {
        return updateType;
    }

    public void setUpdateType(String updateType) {
        this.updateType = updateType;
    }

    public String getVersionName() {
        return versionName;
    }

    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }

    public Integer getScreenOrder() {
        return screenOrder;
    }

    public void setScreenOrder(Integer screenOrder) {
        this.screenOrder = screenOrder;
    }

    /**
     * 多语言 tag名称，JSON格式 viewName:{"viewName": [ { "lang": "zh-CN","content": "乐见" }, { "lang":
     * "en-US", "content": "LeView" } ]}
     */
    public String getScreenTag() {
        return screenTag;
    }

    public void setScreenTag(String screenTag) {
        this.screenTag = screenTag;
    }

    public String getDependModel() {
        return dependModel;
    }

    public void setDependModel(String dependModel) {
        this.dependModel = dependModel;
    }

    public String getVersionCode() {
        return versionCode;
    }

    public void setVersionCode(String versionCode) {
        this.versionCode = versionCode;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getTabName() {
        return tabName;
    }

    public void setTabName(String tabName) {
        this.tabName = tabName;
    }

    public String getBaseVersion() {
        return baseVersion;
    }

    public void setBaseVersion(String baseVersion) {
        this.baseVersion = baseVersion;
    }

    public String getUpdateVersionCode() {
        return updateVersionCode;
    }

    public void setUpdateVersionCode(String updateVersionCode) {
        this.updateVersionCode = updateVersionCode;
    }

    public Boolean getShowOnTab() {
        return checkBoolean(showOnTab);
    }

    public void setShowOnTab(Boolean showOnTab) {
        this.showOnTab = showOnTab;
    }

    public String getFileSize() {
        return fileSize;
    }

    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public String getTagType() {
        return tagType;
    }

    public void setTagType(String tagType) {
        this.tagType = tagType;
    }

    public String getDescribe() {
        return describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getUpdateInfo() {
        return updateInfo;
    }

    public void setUpdateInfo(String updateInfo) {
        this.updateInfo = updateInfo;
    }

    public Boolean getLocked() {
        return checkBoolean(locked);
    }

    public void setLocked(Boolean locked) {
        this.locked = locked;
    }

    public Boolean getIsNew() {
        return checkBoolean(isNew);
    }

    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }

    public Integer getHot() {
        return hot;
    }

    public void setHot(Integer hot) {
        this.hot = hot;
    }

    public String getNotSupport() {
        return notSupport;
    }

    public void setNotSupport(String notSupport) {
        this.notSupport = notSupport;
    }

    public String getMark1() {
        return mark1;
    }

    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }

    public String getMark2() {
        return mark2;
    }

    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }

    public String getMark3() {
        return mark3;
    }

    public void setMark3(String mark3) {
        this.mark3 = mark3;
    }

    public String getMark4() {
        return mark4;
    }

    public void setMark4(String mark4) {
        this.mark4 = mark4;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public Boolean getHasUsed() {
        return checkBoolean(hasUsed);
    }

    public void setHasUsed(Boolean hasUsed) {
        this.hasUsed = hasUsed;
    }

    public String getOfflineShot() {
        return offlineShot;
    }

    public void setOfflineShot(String offlineShot) {
        this.offlineShot = offlineShot;
    }

    public String getPageId() {
        return pageId;
    }

    public void setPageId(String pageId) {
        this.pageId = pageId;
    }

    public boolean isForceUpdateFromXml() {
        return forceUpdateFromXml;
    }

    public void setForceUpdateFromXml(boolean forceUpdateFromXml) {
        this.forceUpdateFromXml = forceUpdateFromXml;
    }

    public boolean isForceChangeTab() {
        return forceChangeTab;
    }

    public void setForceChangeTab(boolean forceChangeTab) {
        this.forceChangeTab = forceChangeTab;
    }

    public boolean isForceAddToTable() {
        return forceAddToTable;
    }

    public void setForceAddToTable(boolean forceAddToTable) {
        this.forceAddToTable = forceAddToTable;
    }

    /**
     * Only temp variables
     */
    public int mSortLevel;
    public boolean isFirstIn;

    private boolean checkBoolean(Boolean b) {
        if (b == null) {
            return false;
        }
        return b;
    }

    /**
     * 优先判断：packageName > tag
     * @param o
     * @return
     */
    @Override
    public boolean equals(Object o) {
        if (o instanceof ScreenInfo) {
            ScreenInfo info = (ScreenInfo) o;
            if (!TextUtils.isEmpty(info.packageName) && info.packageName.equals(this.packageName)) {
                return true;
            }
            return !TextUtils.isEmpty(info.tag) && info.tag.equals(this.tag);
        }
        return false;
    }

    /**
     * Only update parameter in xml
     * <sortable></sortable>
     * <removable></removable>
     * <pluginId></pluginId>
     * <tag></tag>
     * <fileName></fileName>
     * <versionCode></versionCode>
     * <versionName></versionName>
     * <packageName></packageName>
     * <dependModel></dependModel>
     * <pluginType></pluginType>
     * <order></order>
     * <showOnTab></showOnTab>
     * <local></local>
     * @param screenOfXml
     */



    @Override
    public String toString() {
        return "ScreenInfo{" + "id=" + id + ", packageName='" + packageName + '\'' + ", tag='" + tag
                + '\'' + ", name='" + name + '\'' + ", local=" + local + ", sortable=" + sortable
                + ", removable=" + removable + ", pluginUrl='" + pluginUrl + '\'' + ", pluginId="
                + pluginId + ", pluginPath='" + pluginPath + '\'' + ", pluginType='" + pluginType
                + '\'' + ", pluginSize='" + pluginSize + '\'' + ", pluginState='" + pluginState
                + '\'' + ", updateType='" + updateType + '\'' + ", versionName='" + versionName
                + '\'' + ", screenOrder=" + screenOrder + ", screenTag='" + screenTag + '\''
                + ", dependModel='" + dependModel + '\'' + ", versionCode='" + versionCode + '\''
                + ", fileName='" + fileName + '\'' + ", packageName='" + packageName + '\''
                + ", tabName='" + tabName + '\'' + ", baseVersion='" + baseVersion + '\''
                + ", updateVersionCode='" + updateVersionCode + '\'' + ", showOnTab=" + showOnTab
                + ", fileSize='" + fileSize + '\'' + ", md5='" + md5 + '\'' + ", tagType='"
                + tagType + '\'' + ", describe='" + describe + '\'' + ", iconUrl='" + iconUrl + '\''
                + ", imageUrl='" + imageUrl + '\'' + ", updateInfo='" + updateInfo + '\''
                + ", locked=" + locked + ", isNew=" + isNew + ", hot=" + hot + ", notSupport='"
                + notSupport + '\'' + ", mark1='" + mark1 + '\'' + ", mark2='" + mark2 + '\''
                + ", mark3='" + mark3 + '\'' + ", mark4='" + mark4 + '\'' + ", position=" + position
                + ", hasUsed=" + hasUsed + ", offlineShot='" + offlineShot + '\''
                + ", forceChangeTab=" + forceChangeTab + ", forceAddToTable=" + forceAddToTable
                + ", forceUpdateFromXml=" + forceUpdateFromXml + ", pageId='" + pageId + '\''
                + ", mSortLevel=" + mSortLevel + ", isFirstIn=" + isFirstIn + '}';
    }
}
